name: Test Coverage Check and Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov openai
        
    - name: Run tests and check coverage
      run: |
        pytest --cov=src tests/ --cov-report=xml
        
    - name: Generate tests if coverage is low
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python .github/scripts/generate_tests.py
